### ISSUE TITLE
Empty Release Archive

### ISSUE THREAD

**Issue by polyjitter** [Duinrahaic/FitOSC#9]
Hi all! It looks like maybe the release archives are empty? This is observed behavior for all releases, and for both with and without runtime.

![image](https://github.com/user-attachments/assets/50641ca5-a82d-4937-a58e-d91b94abf540)
![image](https://github.com/user-attachments/assets/32782796-7887-456a-96bd-d5dcd7cb347a)

Currently on Windows 11 Pro 23H2.

**Comment by polyjitter** [comment]
Found the issue - looks like in the workflow, you're creating a (gzipped) tarball, but uploading it as a ZIP. Changing it to `.tar.gz` resolves the issue.

Gonna submit a PR to change that to make a zip instead of a tarball :)

![image](https://github.com/user-attachments/assets/4518c527-9bce-41f0-9f02-679aa595dee5)
![image](https://github.com/user-attachments/assets/c5e0b867-3d3f-4d65-8b35-3a68c7a0ff67)

**Comment by Duinrahaic** [comment]
Fixed In #10
